FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim

WORKDIR /app
COPY pyproject.toml .
COPY uv.lock .
RUN uv pip install -r pyproject.toml --system

COPY src src
ENV PYTHONPATH=src

EXPOSE 8080

CMD ["streamlit", "run", "src/Streamlit/app.py", "--server.port=8080", "--server.address=0.0.0.0"]
